# Generated by Django 5.2.1 on 2025-05-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
        ),
    ]
